import { ProgramWeek } from "./types/database";

export const programWeeksData: ProgramWeek[] = [
  {
    id: 1,
    week_number: 1,
    title: "Preparação e Decisão",
    theme: "Preparação e Consciência",
    lesson: "Entendendo a Dependência e Seus Gatilhos: Compreendendo como a nicotina afeta o cérebro e identificando situações que desencadeiam o desejo de fumar.",
    circle: "Compartilhando Experiências e Medos: Criando um ambiente seguro para expressar ansiedades e expectativas sobre parar de fumar.",
    activity: "Diário de Gatilhos e Desejos: Registrando quando, onde e por que você fuma para identificar padrões.",
    checkin: "Registro de Humor e Desejos",
    task_title: "Definindo o Dia D",
    task_description: "Nesta semana, o foco é se preparar mentalmente e fisicamente para parar de fumar. Escolha uma data específica nos próximos 7 dias para ser seu 'Dia D'. Prepare seu ambiente removendo cigarros, cinzeiros e isqueiros. Comunique sua decisão para pessoas próximas que possam te apoiar.",
    tips: [
      "Identifique seus gatilhos: Anote quando, onde e por que você fuma para reconhecer padrões.",
      "Prepare seu ambiente: Remova todos os cigarros, cinzeiros e isqueiros de casa, carro e trabalho.",
      "Comunique sua decisão: Conte para família e amigos sobre seu plano para obter apoio.",
      "Beba bastante água: Ajuda a eliminar a nicotina do corpo e reduz a ansiedade.",
      "Pratique respiração profunda: Técnica útil para momentos de estresse e fissura.",
      "Evite gatilhos conhecidos: Identifique e evite situações que normalmente te fazem fumar.",
      "Tenha substitutos saudáveis: Cenoura, aipo, chicletes sem açúcar para manter a boca ocupada.",
      "Lembre-se dos seus motivos: Escreva uma lista dos motivos pelos quais você quer parar de fumar."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    week_number: 2,
    title: "O Dia D e os Primeiros Desafios",
    theme: "Preparação e Consciência",
    lesson: "Lidando com a Abstinência e a Ansiedade: Entendendo os sintomas e como eles se manifestam.",
    circle: "Estratégias para Superar a Vontade de Fumar: Compartilhando experiências e técnicas que funcionam.",
    activity: "Técnicas de Relaxamento e Respiração: Praticando exercícios para acalmar a mente e o corpo.",
    checkin: "Monitoramento de Sintomas de Abstinência",
    task_title: "Superando os Primeiros Dias",
    task_description: "Nesta semana, o foco é superar os primeiros dias sem cigarro. Utilize as técnicas de respiração profunda e relaxamento. Mantenha-se ocupado e evite gatilhos. Lembre-se que a fissura é passageira.",
    tips: [
      "Os primeiros 3 dias são os mais difíceis: A fissura é mais intensa, mas diminui rapidamente.",
      "Respire fundo: Inspire contando até 4, segure por 7, expire por 8. Repita algumas vezes.",
      "Beba água: Ajuda a eliminar toxinas e a diminuir a vontade de fumar.",
      "Faça exercícios leves: Caminhadas curtas podem aliviar o estresse e a ansiedade.",
      "Distraia-se: Mude o foco da sua atenção quando a vontade de fumar aparecer. Faça algo que goste.",
      "Evite álcool e cafeína: Podem ser gatilhos para o desejo de fumar.",
      "Busque apoio: Converse com seu grupo de apoio, amigos ou familiares sobre o que está sentindo.",
      "Lembre-se dos benefícios: Pense na sua saúde e na liberdade que está conquistando."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    week_number: 3,
    title: "Gerenciando o Estresse e as Emoções",
    theme: "Preparação e Consciência",
    lesson: "A Relação entre Fumo, Estresse e Emoções: Entendendo como o cigarro era usado para lidar com o estresse e como desenvolver novas estratégias.",
    circle: "Compartilhando Formas Saudáveis de Lidar com o Estresse: Troca de experiências sobre técnicas de relaxamento e enfrentamento.",
    activity: "Exercícios de Mindfulness e Meditação Guiada: Praticando a atenção plena para gerenciar a ansiedade e os desejos.",
    checkin: "Avaliação de Níveis de Estresse e Humor",
    task_title: "Desenvolvendo Novas Estratégias de Enfrentamento",
    task_description: "Nesta semana, foque em desenvolver novas formas de lidar com o estresse e as emoções sem recorrer ao cigarro. Experimente técnicas de relaxamento, como respiração profunda, meditação ou yoga. Identifique seus gatilhos emocionais e crie um plano para lidar com eles de forma saudável.",
    tips: [
      "O estresse é um gatilho comum para a recaída: Aprenda a identificá-lo e a lidar com ele de forma saudável.",
      "Mindfulness: A prática da atenção plena pode ajudar a reduzir a ansiedade e a fissura, permitindo que você observe seus pensamentos e emoções sem julgamento.",
      "Exercícios de respiração: Respire profundamente e expire lentamente para acalmar o sistema nervoso.",
      "Atividade física: O exercício é um excelente aliviador de estresse natural.",
      "Conecte-se com a natureza: Passar tempo ao ar livre pode reduzir o estresse e melhorar o humor.",
      "Durma bem: A privação do sono pode aumentar o estresse e a irritabilidade.",
      "Busque apoio: Converse com seu grupo de apoio, amigos ou familiares sobre suas emoções.",
      "Evite o perfeccionismo: Pequenos deslizes podem acontecer, o importante é aprender com eles e seguir em frente."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    week_number: 4,
    title: "Prevenção de Recaídas e Manutenção",
    theme: "Preparação e Consciência",
    lesson: "Reconhecendo Sinais de Alerta e Plano de Ação: Identificando gatilhos e situações de risco para recaídas.",
    circle: "Discutindo Desafios e Vitórias: Compartilhando experiências sobre como superar momentos difíceis e manter a abstinência.",
    activity: "Criação de um Plano de Prevenção de Recaídas: Desenvolvendo estratégias personalizadas para lidar com a vontade de fumar.",
    checkin: "Revisão de Estratégias e Identificação de Riscos",
    task_title: "Fortalecendo sua Resiliência",
    task_description: "Nesta semana, o foco é fortalecer sua resiliência e criar um plano sólido para prevenir recaídas. Identifique seus gatilhos pessoais e desenvolva estratégias específicas para cada um deles. Lembre-se que recaídas são parte do processo de aprendizado, mas não significam falha.",
    tips: [
      "Identifique seus gatilhos: Reconheça as situações, emoções ou pessoas que te fazem querer fumar.",
      "Crie um plano de ação: Para cada gatilho, defina uma estratégia de enfrentamento. Por exemplo, se o estresse é um gatilho, pratique exercícios de respiração.",
      "Evite o primeiro trago: Um único cigarro pode levar a uma recaída completa. Lembre-se que não existe 'só um'.",
      "Aprenda com os deslizes: Se você escorregar, não desista. Analise o que aconteceu, aprenda com a experiência e retome seu plano imediatamente.",
      "Mantenha-se conectado: Continue participando de grupos de apoio ou conversando com seu mentor. O apoio social é fundamental.",
      "Celebre suas conquistas: Reconheça o progresso que você já fez e se recompense de forma saudável.",
      "Mantenha-se hidratado e coma de forma saudável: Uma boa alimentação e hidratação ajudam a manter o corpo e a mente equilibrados.",
      "Pratique a autocompaixão: Seja gentil consigo mesmo. Parar de fumar é um processo desafiador e exige paciência."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    week_number: 5,
    title: "Benefícios da Vida Sem Fumo",
    theme: "Fortalecimento e Mudança",
    lesson: "Os Impactos Positivos na Saúde e Qualidade de Vida: Explorando as melhorias que já podem ser sentidas e as que virão.",
    circle: "Compartilhando as Mudanças Percebidas: Troca de experiências sobre as melhorias no paladar, olfato, respiração e energia.",
    activity: "Lista de Benefícios Pessoais: Criando um registro dos benefícios que você já notou e dos que deseja alcançar.",
    checkin: "Avaliação de Melhorias na Saúde e Bem-estar",
    task_title: "Reconhecer e Valorizar os Benefícios",
    task_description: "Nesta semana, o foco é reconhecer e valorizar os benefícios que você já está colhendo ao parar de fumar. Observe as melhorias na sua respiração, paladar, olfato e níveis de energia. Faça uma lista de todos os benefícios que você já percebeu e use-os como motivação para continuar. Celebre suas conquistas!",
    tips: [
      "Melhora da respiração: Você já deve sentir uma respiração mais fácil e menos tosse.",
      "Paladar e olfato aprimorados: Os alimentos e cheiros se tornam mais intensos e agradáveis.",
      "Mais energia e disposição: A circulação sanguínea melhora, trazendo mais vitalidade.",
      "Pele mais saudável: A pele começa a recuperar o brilho e a elasticidade.",
      "Redução do risco de doenças: A cada dia sem cigarro, seu corpo se recupera e o risco de doenças cardíacas, AVC e câncer diminui.",
      "Liberdade financeira: Calcule quanto você já economizou ao não comprar cigarros e use esse dinheiro para algo que te dê prazer.",
      "Melhora da autoestima: Sinta-se orgulhoso(a) da sua decisão e do controle que você está exercendo sobre sua vida.",
      "Inspire outras pessoas: Sua jornada pode ser uma inspiração para amigos e familiares que também desejam parar de fumar."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    week_number: 6,
    title: "Lidando com o Ganho de Peso",
    theme: "Fortalecimento e Mudança",
    lesson: "Estratégias Nutricionais e Atividade Física: Entendendo o metabolismo e como gerenciar o peso de forma saudável.",
    circle: "Desmistificando o Ganho de Peso Pós-Cessação: Compartilhando experiências e estratégias para lidar com o peso.",
    activity: "Planejamento de Refeições Saudáveis: Criando um plano alimentar equilibrado e saboroso.",
    checkin: "Monitoramento de Peso e Hábitos Alimentares",
    task_title: "Adotando Hábitos Saudáveis para o Peso",
    task_description: "Nesta semana, o foco é adotar hábitos alimentares saudáveis e incorporar a atividade física na sua rotina para gerenciar o peso. Concentre-se em uma alimentação balanceada, rica em frutas, vegetais e proteínas. Mantenha-se ativo e lembre-se que os benefícios de parar de fumar superam qualquer ganho de peso.",
    tips: [
      "Não se preocupe excessivamente com o peso: Os benefícios de parar de fumar superam em muito os riscos de um pequeno ganho de peso.",
      "Alimentação balanceada: Priorize frutas, vegetais, grãos integrais e proteínas magras. Evite alimentos processados e ricos em açúcar.",
      "Beba bastante água: Ajuda a controlar o apetite e a manter o corpo hidratado.",
      "Faça pequenas refeições: Comer porções menores e mais frequentes pode ajudar a controlar a fome.",
      "Mastigue bem os alimentos: Ajuda na digestão e na sensação de saciedade.",
      "Pratique exercícios físicos: A atividade física regular ajuda a queimar calorias, melhora o humor e reduz o estresse.",
      "Evite dietas restritivas: Elas podem levar a compulsões e frustrações. Foque em uma alimentação equilibrada e sustentável.",
      "Converse com um profissional: Se o ganho de peso for uma preocupação, procure um nutricionista ou médico para orientação personalizada."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    week_number: 7,
    title: "Fortalecendo Mente e Corpo",
    theme: "Fortalecimento e Mudança",
    lesson: "Exercício Físico e Bem-Estar Mental: Aprofundando a compreensão sobre como a atividade física impacta a saúde mental e física.",
    circle: "A Importância da Atividade Física na Recuperação: Compartilhando experiências e motivando a prática regular de exercícios.",
    activity: "Rotina de Exercícios Físicos: Criando um plano de exercícios personalizado e divertido.",
    checkin: "Avaliação de Níveis de Energia e Atividade Física",
    task_title: "Movimente-se para o Bem-Estar",
    task_description: "Nesta semana, o foco é integrar a atividade física na sua rotina diária para melhorar o bem-estar físico e mental. Escolha uma atividade que você goste e comece devagar. Lembre-se que o exercício é um poderoso aliado contra o estresse, a ansiedade e a fissura.",
    tips: [
      "Comece devagar: Se você não está acostumado a se exercitar, comece com caminhadas curtas e aumente gradualmente a intensidade e a duração.",
      "Encontre uma atividade que você goste: Dança, natação, yoga, ciclismo, caminhada, corrida – o importante é se divertir e se manter ativo.",
      "Exercício como aliviador de estresse: A atividade física libera endorfinas, que são hormônios do bem-estar, ajudando a reduzir o estresse e a ansiedade.",
      "Melhora do sono: A prática regular de exercícios pode melhorar a qualidade do seu sono.",
      "Aumento da energia: Embora pareça contraditório, o exercício aumenta seus níveis de energia a longo prazo.",
      "Melhora do humor: A atividade física é um excelente antidepressivo natural.",
      "Hidrate-se: Beba bastante água antes, durante e depois dos exercícios.",
      "Consulte um médico: Antes de iniciar qualquer programa de exercícios, converse com seu médico, especialmente se tiver alguma condição de saúde."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    week_number: 8,
    title: "Construindo um Futuro Sem Fumo",
    theme: "Fortalecimento e Mudança",
    lesson: "Planejamento de Metas e Visualização: Definindo objetivos de vida sem o cigarro e visualizando o futuro.",
    circle: "Compartilhando Sonhos e Planos: Inspirando uns aos outros com visões de um futuro saudável e livre do tabaco.",
    activity: "Criação de um Mural de Sonhos: Visualizando metas e aspirações para a vida sem fumo.",
    checkin: "Definição de Objetivos e Metas Futuras",
    task_title: "Construindo seu Futuro Livre do Fumo",
    task_description: "Nesta semana, concentre-se em construir um futuro vibrante e livre do tabaco. Defina metas claras para sua saúde, finanças, relacionamentos e bem-estar geral. Visualize-se alcançando esses objetivos e sinta a motivação para continuar sua jornada.",
    tips: [
      "Defina metas claras e realistas: O que você quer conquistar agora que está livre do cigarro?",
      "Visualize seu sucesso: Imagine-se vivendo uma vida plena e saudável sem o tabaco.",
      "Crie um plano de ação: Divida seus objetivos em passos menores e mais fáceis de alcançar.",
      "Recompense-se: Celebre cada pequena vitória ao longo do caminho.",
      "Mantenha-se positivo: Acredite na sua capacidade de construir um futuro sem fumo.",
      "Busque novas paixões: Descubra hobbies e atividades que te tragam alegria e preenchimento.",
      "Cerque-se de apoio: Mantenha contato com pessoas que te apoiam e te inspiram.",
      "Lembre-se do por que você começou: Relembre os motivos que te levaram a parar de fumar e use-os como motivação."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    week_number: 9,
    title: "Reconhecendo e Lidando com Gatilhos Emocionais",
    theme: "Consolidação e Nova Vida",
    lesson: "Identificando Gatilhos Emocionais: Compreendendo como as emoções afetam o desejo de fumar e como reconhecer seus próprios gatilhos.",
    circle: "Estratégias para Lidar com a Fissura Emocional: Compartilhando técnicas e experiências para superar a vontade de fumar em momentos de estresse, tristeza ou alegria.",
    activity: "Diário de Emoções e Gatilhos: Registrando as emoções e situações que desencadeiam o desejo de fumar para desenvolver estratégias personalizadas.",
    checkin: "Monitoramento de Estados Emocionais e Gatilhos",
    task_title: "Dominando suas Emoções",
    task_description: "Nesta semana, o foco é reconhecer e lidar de forma saudável com os gatilhos emocionais que podem levar ao desejo de fumar. Entenda que o cigarro muitas vezes era uma forma de lidar com emoções, e agora você precisa desenvolver novas estratégias. Use o diário de emoções para identificar padrões e praticar respostas alternativas.",
    tips: [
      "Consciência emocional: Observe suas emoções sem julgamento. Pergunte a si mesmo: 'O que estou sentindo agora?' e 'Como isso me faz querer fumar?'.",
      "Respire fundo: Quando sentir uma emoção intensa, use a respiração profunda para se acalmar antes de reagir.",
      "Identifique seus gatilhos emocionais: Estresse, ansiedade, tristeza, raiva, tédio, alegria excessiva – qualquer emoção pode ser um gatilho.",
      "Desenvolva respostas alternativas: Em vez de acender um cigarro, tente dar uma caminhada, ouvir música, conversar com um amigo, beber água ou praticar meditação.",
      "Mindfulness: A atenção plena pode ajudar a observar a fissura e as emoções sem se deixar levar por elas.",
      "Busque apoio: Converse com seu grupo de apoio ou terapeuta sobre suas dificuldades em lidar com as emoções.",
      "Evite o isolamento: A solidão pode intensificar as emoções negativas. Mantenha-se conectado com pessoas que te fazem bem.",
      "Seja paciente consigo mesmo: Mudar padrões emocionais leva tempo e prática. Celebre cada pequena vitória."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 10,
    week_number: 10,
    title: "Construindo um Estilo de Vida Saudável e Sustentável",
    theme: "Consolidação e Nova Vida",
    lesson: "A Importância da Alimentação, Sono e Exercícios: Entendendo como esses pilares sustentam a abstinência e promovem o bem-estar geral.",
    circle: "Compartilhando Estratégias para um Estilo de Vida Saudável: Troca de experiências sobre como manter uma rotina equilibrada e prazerosa.",
    activity: "Planejamento de Rotina de Bem-Estar: Criando um cronograma diário que inclua alimentação saudável, atividade física e sono adequado.",
    checkin: "Avaliação de Hábitos de Vida e Bem-estar Geral",
    task_title: "Integrando Hábitos Saudáveis",
    task_description: "Nesta semana, o foco é consolidar um estilo de vida saudável e sustentável. Integre a alimentação balanceada, a prática regular de exercícios e um sono de qualidade na sua rotina. Lembre-se que esses hábitos são fundamentais para manter a abstinência e promover seu bem-estar a longo prazo.",
    tips: [
      "Alimentação balanceada: Continue priorizando alimentos integrais, frutas, vegetais e proteínas. Eles fornecem energia e nutrientes essenciais.",
      "Hidrate-se: Beba bastante água ao longo do dia para manter o corpo hidratado e funcionando bem.",
      "Exercício físico regular: Mantenha-se ativo com atividades que você goste. O exercício ajuda a aliviar o estresse, melhorar o humor e controlar o peso.",
      "Higiene do sono: Crie uma rotina relaxante antes de dormir, evite eletrônicos e mantenha o quarto escuro e silencioso para garantir um sono reparador.",
      "Gerenciamento do estresse: Continue praticando técnicas de relaxamento, como meditação, yoga ou respiração profunda, para lidar com o estresse do dia a dia.",
      "Tempo para lazer: Reserve um tempo para atividades que você goste e que te tragam prazer. Isso ajuda a manter o equilíbrio emocional.",
      "Mantenha-se conectado: Continue buscando apoio em seu grupo, amigos e familiares. O suporte social é crucial para a manutenção da abstinência.",
      "Celebre suas conquistas: Reconheça o progresso que você fez e se recompense de forma saudável. Você está construindo uma nova vida!"
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 11,
    week_number: 11,
    title: "Resiliência e Prevenção de Recaídas a Longo Prazo",
    theme: "Consolidação e Nova Vida",
    lesson: "Estratégias para Lidar com Desafios Futuros: Preparando-se para situações de risco e desenvolvendo resiliência para manter a abstinência.",
    circle: "Compartilhando Estratégias de Manutenção: Troca de experiências sobre como lidar com os desafios a longo prazo e manter a motivação.",
    activity: "Plano de Prevenção de Recaídas a Longo Prazo: Desenvolvendo um plano detalhado para lidar com gatilhos e situações de risco no futuro.",
    checkin: "Avaliação de Estratégias de Prevenção e Resiliência",
    task_title: "Fortalecendo sua Resiliência a Longo Prazo",
    task_description: "Nesta semana, o foco é fortalecer sua resiliência e desenvolver um plano de prevenção de recaídas a longo prazo. Reconheça que a jornada é contínua e que desafios podem surgir. Prepare-se para eles, confiando na sua capacidade de superá-los e manter-se livre do tabaco.",
    tips: [
      "Reconheça que a recuperação é um processo contínuo: A abstinência é um compromisso diário. Mantenha-se vigilante e consciente.",
      "Identifique seus gatilhos de alto risco: Situações de estresse intenso, celebrações, ou momentos de tédio podem ser gatilhos. Tenha um plano para cada um.",
      "Desenvolva um plano de ação para recaídas: O que você fará se sentir uma forte vontade de fumar? Quem você vai procurar? Quais estratégias vai usar?",
      "Mantenha-se conectado com seu sistema de apoio: Continue participando de grupos, conversando com seu mentor ou amigos que te apoiam.",
      "Pratique o autocuidado: Cuide da sua saúde física e mental. Durma bem, alimente-se de forma saudável e faça exercícios regularmente.",
      "Celebre suas conquistas: Reconheça o progresso que você fez e se recompense de forma saudável. Isso reforça a motivação.",
      "Aprenda com os erros: Se houver um deslize, não se culpe. Analise o que aconteceu, aprenda com a experiência e retome seu plano imediatamente.",
      "Mantenha a perspectiva: Lembre-se dos motivos que te levaram a parar de fumar e dos benefícios que você já conquistou. Sua saúde e liberdade valem a pena."
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 12,
    week_number: 12,
    title: "Celebrando a Liberdade e o Futuro",
    theme: "Consolidação e Nova Vida",
    lesson: "Celebrando Suas Conquistas: Reconhecendo o caminho percorrido e as vitórias alcançadas na jornada sem fumo.",
    circle: "Compartilhando Histórias de Sucesso: Inspirando uns aos outros com as transformações e a liberdade conquistada.",
    activity: "Planejamento de Metas para o Futuro: Definindo novos objetivos e compromissos para uma vida plena e saudável sem tabaco.",
    checkin: "Reflexão sobre a Jornada e Planejamento Futuro",
    task_title: "Viva sua Liberdade Plenamente",
    task_description: "Parabéns! Você chegou ao final do programa de 12 semanas. Celebre sua liberdade do tabaco e o futuro que você está construindo. Reflita sobre o caminho percorrido, as dificuldades superadas e as conquistas alcançadas. Mantenha o compromisso com sua saúde e bem-estar, e continue inspirando outras pessoas com sua jornada.",
    tips: [
      "Reconheça sua vitória: Você superou um grande desafio e conquistou sua liberdade do tabaco. Sinta orgulho de si mesmo!",
      "Celebre de forma saudável: Recompense-se com algo que te dê prazer e que seja bom para sua saúde, como uma viagem, um novo hobby ou um jantar especial.",
      "Mantenha o compromisso: A jornada continua. Mantenha-se vigilante e consciente dos seus gatilhos, mas confie na sua capacidade de superá-los.",
      "Inspire outras pessoas: Compartilhe sua história com amigos e familiares. Sua experiência pode motivar e ajudar outras pessoas a parar de fumar.",
      "Continue aprendendo: A vida é um processo contínuo de aprendizado. Busque novos conhecimentos e experiências que te ajudem a crescer e a se desenvolver.",
      "Viva plenamente: Aproveite a vida sem as amarras do cigarro. Respire fundo, saboreie cada momento e desfrute da sua nova liberdade.",
      "Seja grato: Agradeça a si mesmo, ao seu sistema de apoio e a todos que te ajudaram nessa jornada.",
      "Defina novos objetivos: O que você quer conquistar agora que está livre do tabaco? Sonhe alto e continue construindo a vida que você deseja."
    ],
    created_at: new Date().toISOString(),
  },
];

